/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package skygge;

/**
 *
 * @author json
 */
public class SkyggeFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public SkyggeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel16 = new javax.swing.JPanel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        statusBarLabel = new javax.swing.JLabel();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jPanel7 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        playSentenceButton = new javax.swing.JButton();
        loopSentenceButton = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        sentenceWaveForm = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        showLibraryButton = new javax.swing.JButton();
        showSentenceInfoButton = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(32767, 8));
        jSeparator1 = new javax.swing.JSeparator();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(32767, 8));
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        playRecordingButton = new javax.swing.JButton();
        recordRecordingButton = new javax.swing.JToggleButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        recordingWaveForm = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setResizable(false);

        jPanel16.setLayout(new java.awt.BorderLayout());
        jPanel16.add(filler12, java.awt.BorderLayout.WEST);

        statusBarLabel.setText("Hotkeys: P/L to play/loop sentence, S/R to play/record yourself.");
        jPanel16.add(statusBarLabel, java.awt.BorderLayout.CENTER);
        jPanel16.add(filler13, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel16, java.awt.BorderLayout.SOUTH);

        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel7.add(filler1, java.awt.BorderLayout.LINE_START);
        jPanel7.add(filler2, java.awt.BorderLayout.LINE_END);
        jPanel7.add(filler3, java.awt.BorderLayout.PAGE_END);
        jPanel7.add(filler4, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jPanel9.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(60, 100));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        playSentenceButton.setIcon(new javax.swing.ImageIcon("/Users/json/Dropbox/skygge/icons/media-playback-start.png")); // NOI18N
        playSentenceButton.setPreferredSize(new java.awt.Dimension(50, 50));
        playSentenceButton.setSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel2.add(playSentenceButton, gridBagConstraints);

        loopSentenceButton.setIcon(new javax.swing.ImageIcon("/Users/json/Dropbox/skygge/icons/view-refresh.png")); // NOI18N
        loopSentenceButton.setPreferredSize(new java.awt.Dimension(50, 50));
        loopSentenceButton.setSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(loopSentenceButton, gridBagConstraints);

        filler7.setSize(new java.awt.Dimension(10, 0));
        jPanel2.add(filler7, new java.awt.GridBagConstraints());

        jPanel9.add(jPanel2, java.awt.BorderLayout.LINE_START);

        sentenceWaveForm.setBackground(new java.awt.Color(51, 51, 51));
        sentenceWaveForm.setMaximumSize(new java.awt.Dimension(32767, 100));
        sentenceWaveForm.setMinimumSize(new java.awt.Dimension(600, 100));
        sentenceWaveForm.setPreferredSize(new java.awt.Dimension(600, 100));

        javax.swing.GroupLayout sentenceWaveFormLayout = new javax.swing.GroupLayout(sentenceWaveForm);
        sentenceWaveForm.setLayout(sentenceWaveFormLayout);
        sentenceWaveFormLayout.setHorizontalGroup(
            sentenceWaveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        sentenceWaveFormLayout.setVerticalGroup(
            sentenceWaveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.add(sentenceWaveForm, java.awt.BorderLayout.CENTER);

        jPanel11.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel11.setLayout(new java.awt.GridBagLayout());
        jPanel11.add(filler9, new java.awt.GridBagConstraints());

        showLibraryButton.setIcon(new javax.swing.ImageIcon("/Users/json/Dropbox/skygge/icons/music-library.png")); // NOI18N
        showLibraryButton.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel11.add(showLibraryButton, gridBagConstraints);

        showSentenceInfoButton.setIcon(new javax.swing.ImageIcon("/Users/json/Dropbox/skygge/icons/help-about.png")); // NOI18N
        showSentenceInfoButton.setActionCommand("I");
        showSentenceInfoButton.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel11.add(showSentenceInfoButton, gridBagConstraints);

        jPanel9.add(jPanel11, java.awt.BorderLayout.LINE_END);

        jPanel8.add(jPanel9);
        jPanel8.add(filler6);
        jPanel8.add(jSeparator1);
        jPanel8.add(filler5);

        jPanel12.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jPanel12.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel13.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        playRecordingButton.setIcon(new javax.swing.ImageIcon("/Users/json/Dropbox/skygge/icons/media-playback-start.png")); // NOI18N
        playRecordingButton.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel13.add(playRecordingButton, gridBagConstraints);

        recordRecordingButton.setIcon(new javax.swing.ImageIcon("/Users/json/Dropbox/skygge/icons/media-record.png")); // NOI18N
        recordRecordingButton.setMaximumSize(new java.awt.Dimension(50, 50));
        recordRecordingButton.setMinimumSize(new java.awt.Dimension(50, 50));
        recordRecordingButton.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel13.add(recordRecordingButton, gridBagConstraints);
        jPanel13.add(filler10, new java.awt.GridBagConstraints());

        jPanel12.add(jPanel13, java.awt.BorderLayout.LINE_START);

        recordingWaveForm.setBackground(new java.awt.Color(51, 51, 51));
        recordingWaveForm.setMaximumSize(new java.awt.Dimension(32767, 100));
        recordingWaveForm.setMinimumSize(new java.awt.Dimension(600, 100));
        recordingWaveForm.setPreferredSize(new java.awt.Dimension(600, 100));

        javax.swing.GroupLayout recordingWaveFormLayout = new javax.swing.GroupLayout(recordingWaveForm);
        recordingWaveForm.setLayout(recordingWaveFormLayout);
        recordingWaveFormLayout.setHorizontalGroup(
            recordingWaveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        recordingWaveFormLayout.setVerticalGroup(
            recordingWaveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel12.add(recordingWaveForm, java.awt.BorderLayout.CENTER);

        jPanel15.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel15.setLayout(new java.awt.GridBagLayout());
        jPanel15.add(filler11, new java.awt.GridBagConstraints());

        jPanel12.add(jPanel15, java.awt.BorderLayout.LINE_END);

        jPanel8.add(jPanel12);

        jPanel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkyggeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkyggeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkyggeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkyggeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SkyggeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loopSentenceButton;
    private javax.swing.JButton playRecordingButton;
    private javax.swing.JButton playSentenceButton;
    private javax.swing.JToggleButton recordRecordingButton;
    private javax.swing.JPanel recordingWaveForm;
    private javax.swing.JPanel sentenceWaveForm;
    private javax.swing.JButton showLibraryButton;
    private javax.swing.JButton showSentenceInfoButton;
    private javax.swing.JLabel statusBarLabel;
    // End of variables declaration//GEN-END:variables
}
