/*
 * Copyright (C) 2014 J. Soendermann
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package skygge;

import java.awt.event.*;
/**
 *
 * @author json
 */
public class SkyggeFrame extends javax.swing.JFrame {
    
    private byte[] recordedAudioData;

    /**
     * Creates new form NewJFrame1
     */
    public SkyggeFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel16 = new javax.swing.JPanel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        statusBarLabel = new javax.swing.JLabel();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jPanel7 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        playSentenceButton = new javax.swing.JButton();
        loopSentenceButton = new javax.swing.JToggleButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        sentenceWaveFormPanel = new skygge.WaveFormPanel();
        jPanel11 = new javax.swing.JPanel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        showLibraryButton = new javax.swing.JButton();
        showSentenceInfoButton = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(32767, 8));
        jSeparator1 = new javax.swing.JSeparator();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(32767, 8));
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        playRecordingButton = new javax.swing.JButton();
        recordRecordingButton = new javax.swing.JToggleButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        recordingWaveFormPanel = new skygge.WaveFormPanel();
        jPanel15 = new javax.swing.JPanel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setResizable(false);

        jPanel16.setLayout(new java.awt.BorderLayout());
        jPanel16.add(filler12, java.awt.BorderLayout.WEST);

        statusBarLabel.setText("Hotkeys: P/L to play/loop sentence, S/R to play/record yourself.");
        jPanel16.add(statusBarLabel, java.awt.BorderLayout.CENTER);
        jPanel16.add(filler13, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel16, java.awt.BorderLayout.SOUTH);

        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel7.add(filler1, java.awt.BorderLayout.LINE_START);
        jPanel7.add(filler2, java.awt.BorderLayout.LINE_END);
        jPanel7.add(filler3, java.awt.BorderLayout.PAGE_END);
        jPanel7.add(filler4, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jPanel9.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(60, 100));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        playSentenceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media-playback-start.png"))); // NOI18N
        playSentenceButton.setPreferredSize(new java.awt.Dimension(50, 50));
        playSentenceButton.setSize(new java.awt.Dimension(50, 50));
        playSentenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSentenceButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel2.add(playSentenceButton, gridBagConstraints);

        loopSentenceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view-refresh.png"))); // NOI18N
        loopSentenceButton.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(loopSentenceButton, gridBagConstraints);
        jPanel2.add(filler7, new java.awt.GridBagConstraints());

        jPanel9.add(jPanel2, java.awt.BorderLayout.LINE_START);

        sentenceWaveFormPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        sentenceWaveFormPanel.setMinimumSize(new java.awt.Dimension(600, 100));
        sentenceWaveFormPanel.setPreferredSize(new java.awt.Dimension(600, 100));

        javax.swing.GroupLayout sentenceWaveFormPanelLayout = new javax.swing.GroupLayout(sentenceWaveFormPanel);
        sentenceWaveFormPanel.setLayout(sentenceWaveFormPanelLayout);
        sentenceWaveFormPanelLayout.setHorizontalGroup(
            sentenceWaveFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        sentenceWaveFormPanelLayout.setVerticalGroup(
            sentenceWaveFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        jPanel9.add(sentenceWaveFormPanel, java.awt.BorderLayout.CENTER);

        jPanel11.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel11.setLayout(new java.awt.GridBagLayout());
        jPanel11.add(filler9, new java.awt.GridBagConstraints());

        showLibraryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/music-library.png"))); // NOI18N
        showLibraryButton.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel11.add(showLibraryButton, gridBagConstraints);

        showSentenceInfoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help-about.png"))); // NOI18N
        showSentenceInfoButton.setActionCommand("I");
        showSentenceInfoButton.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel11.add(showSentenceInfoButton, gridBagConstraints);

        jPanel9.add(jPanel11, java.awt.BorderLayout.LINE_END);

        jPanel8.add(jPanel9);
        jPanel8.add(filler6);
        jPanel8.add(jSeparator1);
        jPanel8.add(filler5);

        jPanel12.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jPanel12.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel13.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        playRecordingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media-playback-start.png"))); // NOI18N
        playRecordingButton.setPreferredSize(new java.awt.Dimension(50, 50));
        playRecordingButton.setSize(new java.awt.Dimension(50, 50));
        playRecordingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playRecordingButtonActionPerformed(evt);
            }
        });
        jPanel13.add(playRecordingButton, new java.awt.GridBagConstraints());

        recordRecordingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media-record.png"))); // NOI18N
        recordRecordingButton.setMaximumSize(new java.awt.Dimension(50, 50));
        recordRecordingButton.setMinimumSize(new java.awt.Dimension(50, 50));
        recordRecordingButton.setPreferredSize(new java.awt.Dimension(50, 50));
        recordRecordingButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                recordRecordingButtonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel13.add(recordRecordingButton, gridBagConstraints);
        jPanel13.add(filler10, new java.awt.GridBagConstraints());

        jPanel12.add(jPanel13, java.awt.BorderLayout.LINE_START);

        recordingWaveFormPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        recordingWaveFormPanel.setMinimumSize(new java.awt.Dimension(600, 100));
        recordingWaveFormPanel.setPreferredSize(new java.awt.Dimension(600, 100));

        javax.swing.GroupLayout recordingWaveFormPanelLayout = new javax.swing.GroupLayout(recordingWaveFormPanel);
        recordingWaveFormPanel.setLayout(recordingWaveFormPanelLayout);
        recordingWaveFormPanelLayout.setHorizontalGroup(
            recordingWaveFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        recordingWaveFormPanelLayout.setVerticalGroup(
            recordingWaveFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        jPanel12.add(recordingWaveFormPanel, java.awt.BorderLayout.CENTER);

        jPanel15.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel15.setLayout(new java.awt.GridBagLayout());
        jPanel15.add(filler11, new java.awt.GridBagConstraints());

        jPanel12.add(jPanel15, java.awt.BorderLayout.LINE_END);

        jPanel8.add(jPanel12);

        jPanel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recordRecordingButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_recordRecordingButtonItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            AudioManager.getAudioManagerInstance().stopEverything();
            AudioManager.getAudioManagerInstance().startRecording();
        } else if(evt.getStateChange()==ItemEvent.DESELECTED){
            AudioManager.getAudioManagerInstance().stopEverything();
            recordedAudioData = AudioManager.getAudioManagerInstance().getRecordedAudioData();
            recordingWaveFormPanel.setAudioData(recordedAudioData);
        }
    }//GEN-LAST:event_recordRecordingButtonItemStateChanged

    private void playSentenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playSentenceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playSentenceButtonActionPerformed

    private void playRecordingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playRecordingButtonActionPerformed
        if (recordedAudioData != null) {
            AudioManager.getAudioManagerInstance().stopEverything();
            AudioManager.getAudioManagerInstance().startPlaying(recordedAudioData);
            
        }
    }//GEN-LAST:event_playRecordingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton loopSentenceButton;
    private javax.swing.JButton playRecordingButton;
    private javax.swing.JButton playSentenceButton;
    private javax.swing.JToggleButton recordRecordingButton;
    private skygge.WaveFormPanel recordingWaveFormPanel;
    private skygge.WaveFormPanel sentenceWaveFormPanel;
    private javax.swing.JButton showLibraryButton;
    private javax.swing.JButton showSentenceInfoButton;
    private javax.swing.JLabel statusBarLabel;
    // End of variables declaration//GEN-END:variables
}
