/*
 * Copyright (C) 2014 json
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package skygge.UI;

import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

/**
 *
 * @author json
 */
public class SentenceInfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form SentenceInfoFrame
     */
    public SentenceInfoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Sentence Info");
        setMinimumSize(null);
        setPreferredSize(new java.awt.Dimension(320, 145));
        setSize(new java.awt.Dimension(320, 140));

        jScrollPane1.setMinimumSize(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(310, 135));
        jScrollPane1.setSize(new java.awt.Dimension(310, 135));

        infoTextArea.setEditable(false);
        infoTextArea.setColumns(20);
        infoTextArea.setRows(5);
        infoTextArea.setText("Chinese (simp): 燕子的尾巴像剪刀。\nPinyin: Yan4zi de wei3ba xiang4 jian3dao1.\nEnglish: The swallow has a forked tail.");
        infoTextArea.setMinimumSize(null);
        infoTextArea.setPreferredSize(null);
        infoTextArea.setSize(new java.awt.Dimension(300, 125));
        jScrollPane1.setViewportView(infoTextArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Ctrl-c to copy.");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setInformation(List<Entry<String, String>> information) {
        String s = "";
        
        for (Entry<String, String> entry : information) {
            s += (String)entry.getKey();
            s += ": ";
            s += (String)entry.getValue();
            s += "\n";
            
            infoTextArea.setText(s);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
