/*
 * Copyright (C) 2014 J. Soendermann
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package skygge.UI;

import java.awt.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.minidev.json.*;
import net.minidev.json.parser.ParseException;
import skygge.Sentence;
import skygge.SentencePack;
import skygge.Utils;

/**
 *
 * @author json
 */
public class SentenceLibraryFrame extends javax.swing.JFrame {
    private SkyggeFrame skyggeFrame;
    
    private List<SentencePack> sentencePacks;
    
    private final String URL_SENTENCE_DATA = "https://skygge.s3.amazonaws.com/sentence_data.json";
    
    /**
     * Creates new form SentenceLibraryFrame
     */
    public SentenceLibraryFrame(SkyggeFrame skyggeFrame) {
        initComponents();
        
        this.skyggeFrame = skyggeFrame;
        
        Utils.setIconOnFrame(this);
        
        sentencePacks = new ArrayList<SentencePack>();
        
        Thread t = new Thread() {
            public void run() {
                try {
                    String sentenceDataString = Utils.loadUrlIntoString(URL_SENTENCE_DATA);
                    
                    Object sentenceData = JSONValue.parseStrict(sentenceDataString);
                    JSONObject sentenceDataObject = (JSONObject)sentenceData;
                    
                    JSONObject languagesMap = (JSONObject)sentenceDataObject.get("languages");
                    JSONArray chineseSentencePacksData = (JSONArray)languagesMap.get("Chinese");
                    
                    for (int i = 0; i < chineseSentencePacksData.size(); i++) {
                        sentencePacks.add(new SentencePack((JSONObject)chineseSentencePacksData.get(i)));
                    }
                    
                    DefaultListModel sentencePackListModel = new DefaultListModel();
                    for (int i = 0; i < sentencePacks.size(); i++) {
                        sentencePackListModel.addElement(sentencePacks.get(i));
                    }
                    
                    final DefaultListModel sentencePackListModelFinalCopy = sentencePackListModel;
                    EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            sentencePackList.setModel(sentencePackListModelFinalCopy);
                    
                            sentencePackList.setSelectedIndex(0);
                            sentencePackSelected(0);
                        }
                    });
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Unable to load sentence library.", 
                        "IO Error", JOptionPane.ERROR_MESSAGE);
                    // Change "Loading..." string in both lists to something else
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "Unable to parse sentence library.", 
                        "IO Error", JOptionPane.ERROR_MESSAGE);
                    // Change "Loading..." string in both lists to something else
                }
            }
        };
        t.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        sentenceCollectionList = new javax.swing.JList();
        jSplitPane3 = new javax.swing.JSplitPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        sentencePackList = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        sentenceList = new javax.swing.JList();

        setLocation(new java.awt.Point(100, 100));

        jPanel1.setMinimumSize(new java.awt.Dimension(178, 70));
        jPanel1.setPreferredSize(new java.awt.Dimension(453, 40));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton);

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        jPanel1.add(openButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jSplitPane2.setDividerLocation(100);
        jSplitPane2.setPreferredSize(new java.awt.Dimension(162, 300));

        jScrollPane3.setMinimumSize(new java.awt.Dimension(50, 23));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(50, 140));
        jScrollPane3.setSize(new java.awt.Dimension(50, 140));

        sentenceCollectionList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Custom", "Mandarin", "Japanese", "German", "English", "Cantonese" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        sentenceCollectionList.setMaximumSize(new java.awt.Dimension(100, 85));
        sentenceCollectionList.setMinimumSize(new java.awt.Dimension(50, 85));
        sentenceCollectionList.setPreferredSize(new java.awt.Dimension(50, 85));
        sentenceCollectionList.setSize(new java.awt.Dimension(50, 136));
        jScrollPane3.setViewportView(sentenceCollectionList);

        jSplitPane2.setLeftComponent(jScrollPane3);

        jSplitPane3.setDividerLocation(120);

        sentencePackList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Animals 2", "Ships", "At the Doctor's", "Japan" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(sentencePackList);

        jSplitPane3.setLeftComponent(jScrollPane4);

        sentenceList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(sentenceList);

        jSplitPane3.setRightComponent(jScrollPane5);

        jSplitPane2.setRightComponent(jSplitPane3);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        loadSentence();
    }//GEN-LAST:event_openButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void loadSentence() {
        Sentence selectedSentence = (Sentence)sentenceList.getSelectedValue();
        skyggeFrame.loadSentence(selectedSentence);
        this.setVisible(false);
    }
    private void sentencePackSelected(int index) {
        SentencePack sentencePack = sentencePacks.get(index);
        
        DefaultListModel sentenceListModel = new DefaultListModel();
        
        for (Sentence sentence : sentencePack.getSentences()) {
            sentenceListModel.addElement(sentence);
        }
        
        sentenceList.setModel(sentenceListModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JButton openButton;
    private javax.swing.JList sentenceCollectionList;
    private javax.swing.JList sentenceList;
    private javax.swing.JList sentencePackList;
    // End of variables declaration//GEN-END:variables
}
